export const ROLES = {
  ADMIN: "ADMIN",
  PROJECT_MANAGER: "PROJECT_MANAGER",
  PROJECT_LEAD: "PROJECT_LEAD",
  TEAM_LEAD: "TEAM_LEAD",
  DEVELOPER: "DEVELOPER",
  TESTER: "TESTER",
  QA: "QA",
};

export const MEMBER_ROLES = [
  ROLES.DEVELOPER,
  ROLES.TESTER,
  ROLES.QA,
];